---
version: "3.7"

services:

  # override build args for oci-env's _base image/service
  # PYTHON_VERSION: 
  #   this influences the switch_python command found
  #   in the oci-env default Dockerfile.
  #   It will install the appropriate python package
  #   if available and then use the alternatives
  #   command to "switch" the whole system over to
  #   that version as best it can.
  # BASE_IMAGE: 
  #   when pulp produces a python 3.11 base image
  #   we can change the BASE_IMAGE setting instead
  #   of invoking swith_python via the PYTHON_VERSION
  #   setting.
  _base:
    build:
      args:
        PYTHON_VERSION: 3.11
        # BASE_IMAGE: ghcr.io/pulp/pulp-ci-centos:latest

  # pre installs all of the python dependencies, including for integration tests
  _galaxy_base:
    depends_on:
      - _base
    build:
      context: "{SRC_DIR}/galaxy_ng/"
      dockerfile: "profiles/base/Dockerfile"
    image: "localhost/oci_env/galaxy_ng:base"
    entrypoint: "/bin/true"

  pulp:
    image: "localhost/oci_env/galaxy_ng:base"
    # this is required in order to run podman inside the container
    privileged: true
    extra_hosts:
      localhost: "host-gateway"
    environment:
      PULP_WORKERS: "1"
      #LOCK_REQUIREMENTS=0
    volumes:
      - "pulp_certs:/etc/pulp/certs/"
    depends_on:
      - _galaxy_base

volumes:
  pulp_certs:
