---
version: "3.7"

services:
  proxy:
    build:
      context: "{SRC_DIR}/galaxy_ng/profiles/insights/proxy"
    ports:
      - "{INSIGHTS_PROXY_PORT}:{INSIGHTS_PROXY_PORT}"
    environment:
      UPSTREAM_URL: "http://pulp:{API_PORT}"
      PROXY_PORT: "{INSIGHTS_PROXY_PORT}"
    volumes:
      - "{SRC_DIR}/galaxy_ng/profiles/insights/proxy:/app:ro"
