---
version: "3.7"

services:
  proxy:
    build:
      context: '{SRC_DIR}/galaxy_ng/profiles/insights/proxy'
    ports:
      - "8080:8080"
    environment:
      UPSTREAM_URL: "http://pulp:{API_PORT}"
    volumes:
      - '{SRC_DIR}/galaxy_ng/profiles/insights/proxy:/app:ro'