---
version: "3.7"

services:
  api:
    env_file:
      - './standalone-keycloak/galaxy_ng.env'
      - '../.compose.env'
  worker:
    env_file:
      - './standalone-keycloak/galaxy_ng.env'
      - '../.compose.env'
  content-app:
    env_file:
      - './standalone-keycloak/galaxy_ng.env'
      - '../.compose.env'
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    env_file:
      - './standalone-keycloak/keycloak.env'
      - '../.compose.env'
    ports:
      - 8080:8080
    depends_on:
      - kc-postgres
      - ldap

  kc-postgres:
    image: "postgres:12"
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    env_file:
      - './standalone-keycloak/kc-postgres.env'
      - '../.compose.env'
    
  ldap:
    image: "rroemhild/test-openldap"
    ports:
      - "10389:10389"
      - "10636:10636"

volumes:
  kc_pg_data:
    name: kc_pg_data${DEV_VOLUME_SUFFIX:-}
