
version: "3.7"

services:
  github:
    build:
      context: '{SRC_DIR}/galaxy_ng/profiles/community/github_mock'
    ports:
      - "8082:8082"
    environment:
      UPSTREAM_PROTO: 'http'
      UPSTREAM_HOST: api
      UPSTREAM_PORT: 8000
    volumes:
      - '{SRC_DIR}/galaxy_ng/profiles/community/github_mock:/app:ro'
