#!/bin/bash

set -o nounset
set -o errexit

declare -xr DEV_SOURCE_PATH=${DEV_SOURCE_PATH:-galaxy_ng}

declare -xr COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-galaxy_ng}"
declare -xr COMPOSE_FILE="${COMPOSE_FILE:-dev/docker-compose.yml}"

declare -xr COMPOSE_CONTEXT=".."


exec docker-compose "$@"
