#!/bin/bash

set -o nounset
set -o errexit

if [[ -f '.compose.env' ]]; then
  set -o allexport
  # avoid override already set variables
  source <(grep -v '^#' .compose.env | sed -E 's|^(.+)=(.*)$|: ${\1=\2}; export \1|g')
  set +o allexport
fi

if [[ -z "${COMPOSE_PROFILE:-}" ]]; then
  cat >&2 <<EOF
ERROR: The \$COMPOSE_PROFILE environment variable MUST be set.
       The the easiest way to to this is to create a .compose.env file by running:

           \$ cp .compose.env.example .compose.env
EOF
  exit 1
fi

echo "INFO: Using compose profile ${COMPOSE_PROFILE}"
echo "INFO: Installing from source ${DEV_SOURCE_PATH}"
echo "INFO: Image suffix ${DEV_IMAGE_SUFFIX}"
echo "INFO: Volume suffix ${DEV_VOLUME_SUFFIX}"

compose_args=(
  -f 'dev/docker-compose.yml'
  -f "dev/${COMPOSE_PROFILE}/docker-compose.yml"
)

if [[ -z "${ANSIBLE_HUB_UI_PATH:-}" ]]; then
    cat >&2 << EOF
INFO: \$ANSIBLE_HUB_UI_PATH is unset.
    If you want to run the UI inside compose please set \$ANSIBLE_HUB_UI_PATH
    to the location of your local copy of https://github.com/ansible/ansible-hub-ui.
EOF
else
    compose_args+=(
      -f 'dev/common/docker-compose-ui.yaml'
      -f "dev/${COMPOSE_PROFILE}/docker-compose-ui.yaml"
    )
fi

declare -xr DEV_SOURCE_PATH=${DEV_SOURCE_PATH:-galaxy_ng}
declare -xr COMPOSE_CONTEXT=".."
declare -xr LOCK_REQUIREMENTS="${LOCK_REQUIREMENTS:-1}"
declare -xr COMPOSE_PROFILE="${COMPOSE_PROFILE}"
declare -xr DEV_IMAGE_SUFFIX="${DEV_IMAGE_SUFFIX:-}"
declare -xr DEV_VOLUME_SUFFIX="${DEV_VOLUME_SUFFIX:-$DEV_IMAGE_SUFFIX}"
declare -xr COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-galaxy_ng${DEV_IMAGE_SUFFIX:-}}"

exec docker-compose "${compose_args[@]}" "$@"
