- name: "Make /opt/oci_env/base/container_scripts"
  file:
    name: /opt/oci_env/base/container_scripts
    state: directory

- name: "Get the dynaconf script"
  command:
    cmd: "curl -o /opt/oci_env/base/container_scripts/get_dynaconf_var.sh https://raw.githubusercontent.com/pulp/oci_env/main/base/container_scripts/get_dynaconf_var.sh"

#- name: install the pulpcli
#  command:
#    cmd: "pip3 install pulp-cli"

#- name: "run pulp config"
#  shell: |
#      #/bin/bash
#      PULP_API_ROOT="/api/galaxy/pulp/"
#      pulp config create --base-url https://pulp --api-root "$PULP_API_ROOT"

- name: "Install pulp-smash"
  command:
    #cmd: "pip3 show pulp-smash || pip3 install git+https://github.com/pulp/pulp-smash.git"
    cmd: "pip3 install git+https://github.com/pulp/pulp-smash.git"

- name: "Get the pulp-smash setup script"
  command:
    cmd: "curl -o /tmp/configure_pulp_smash.sh https://raw.githubusercontent.com/pulp/oci_env/main/base/container_scripts/configure_pulp_smash.sh"

- name: "Run the pulp smash config"
  command:
    cmd: "bash /tmp/configure_pulp_smash.sh"
  environment:
    API_HOST: "pulp"
    API_PORT: "443"
    API_PROTOCOL: "https"
    DJANGO_SUPERUSER_USERNAME: "admin"
    DJANGO_SUPERUSER_PASSWORD: "password"

- name: "Make sure the smash config was made correctly"
  command: "jq . /opt/settings/pulp_smash/settings.json"

- name: "Set perms on the pulp_smash directory"
  file:
      path: ~/.config/pulp_smash/
      state: directory
      mode: "0777"

- name: "Copy settings to config dir"
  shell: "cp -f /opt/settings/pulp_smash/settings.json ~/.config/pulp_smash/setting.json"

- name: "Set perms on the pulp_smash settings file"
  file:
      path: ~/.config/pulp_smash/setting.json
      state: file
      mode: "0666"

- name: "Setup the ca-certs directory"
  file:
      path: /usr/local/share/ca-certificates/
      state: directory

- name: "Copy the cert to the ca folder"
  shell: cp -f /etc/pulp/certs/pulp_webserver.crt /usr/local/share/ca-certificates/.

#- name: "Add the CA cert"
#  script:
#    interpreter: /bin/bash
#    content: |
#      #!/bin/bash
#      # Hack: adding pulp CA to certifi.where()
#      CERTIFI=$(python3 -c 'import certifi; print(certifi.where())')
#      cat /usr/local/share/ca-certificates/pulp_webserver.crt | sudo tee -a "$CERTIFI" > /dev/null
#      if [[ "$TEST" = "azure" ]]; then
#        cat /usr/local/share/ca-certificates/azcert.crt | sudo tee -a "$CERTIFI" > /dev/null
#      fi
#      # Hack: adding pulp CA to default CA file
#      CERT=$(python3 -c 'import ssl; print(ssl.get_default_verify_paths().openssl_cafile)')
#      cat "$CERTIFI" | sudo tee -a "$CERT" > /dev/null
#      # update-ca-certificates
