---
version: "3.7"

services:
  api:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'
    volumes:
      - './standalone-community/galaxy-importer.cfg:/etc/galaxy-importer/galaxy-importer.cfg:z'
  worker:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'
    volumes:
      - './standalone-community/galaxy-importer.cfg:/etc/galaxy-importer/galaxy-importer.cfg:z'
  content-app:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'

  # NOTE: you will need https://addons.mozilla.org/en-US/firefox/addon/cross-domain-cors/
  swagger-ui:
   image: swaggerapi/swagger-ui
   ports:
      - "8003:8080"
   environment:
      API_URL: http://0.0.0.0:5001/api/v3/openapi.json

  galaxy-mirror:
    hostname: galaxy-mirror
    image: jtanner0/galaxy-mirror:3.0
    volumes:
      - './standalone-community/data:/data:rw'

  github:
    build:
      context: './standalone-community/github_mock'
    ports:
      - "8082:8082"
    environment:
      UPSTREAM_PROTO: 'http'
      UPSTREAM_HOST: api
      UPSTREAM_PORT: 8000
    volumes:
      - './standalone-community/github_mock:/app:ro'

