#!/bin/bash

set -x

profile=$1
echo "USING PROFILE ${profile}"

# find the oci-env checkout
if [[ -z $OCI_ENV_PATH ]]; then
    OCI_ENV_PATH=$(dirname $(pip show oci-env | egrep ^Location | awk '{print $2}'))
fi
echo "FOUND OCI_ENV_PATH: ${OCI_ENV_PATH}"

export COMPOSE_INTERACTIVE_NO_CLI=1
env_path=dev/oci_env_integration/oci_env_configs/$profile.compose.env
oci-env -e ${env_path} poll
