#!/bin/bash

set -x

profile=$1
shift
echo "USING PROFILE ${profile}"

# find the oci-env checkout
OCI_ENV_PATH=$(dirname $(pip show oci-env | egrep ^Location | awk '{print $2}'))
echo "FOUND OCI_ENV_PATH: ${OCI_ENV_PATH}"

export COMPOSE_INTERACTIVE_NO_CLI=1
env_path=dev/oci_env_integration/oci_env_configs/$profile.compose.env
oci-env -e ${env_path} compose exec pulp /bin/bash \
    -c "cd /src/galaxy_ng && /tmp/gng_testing/bin/pytest \
            --ignore=galaxy_ng/_vendor \
            --ignore=galaxy_ng/tests/unit \
            --ignore=galaxy_ng/tests/functional \
            --ignore=galaxy_ng/tests/performance \
            -v $@ galaxy_ng/tests/integration"
