# Generated by Django 2.2.15 on 2020-08-11 19:44

from django.db import migrations

def convert_namespace_groups_to_permissions(apps, schema_editor):
    NamespaceModel = apps.get_model('galaxy', 'Namespace')
    for namespace in NamespaceModel.objects.all():
        for group in namespace.groups.all():
            assign_perm('galaxy.change_namespace', group, namespace)
            assign_perm('galaxy.view_namespace', group, namespace)


def convert_synclist_groups_to_permissions(apps, schema_editor):
    SyncListModel = apps.get_model('galaxy', 'SyncList')
    for synclist in SyncListModel.objects.all():
        for group in synclist.groups.all():
            assign_perm('galaxy.change_synclist', group, synclist)
            assign_perm('galaxy.view_synclist', group, synclist)



class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_inbound_repo_per_namespace'),
    ]

    operations = [
        migrations.RunPython(
            code=convert_namespace_groups_to_permissions,
        ),
        migrations.RemoveField(
            model_name='namespace',
            name='groups',
        ),
        migrations.RunPython(
            code=convert_synclist_groups_to_permissions,
        ),
        migrations.RemoveField(
            model_name='synclist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='synclist',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='namespace',
            options={'permissions': (('upload_to_namespace', 'Upload collections to namespace'),)},
        ),
    ]
