# Generated by Django 2.2.14 on 2020-08-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_export_to_chunks'),
        ('ansible', '0019_collection_token'),
        ('galaxy', '0003_inbound_repo_per_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible.AnsibleRepository')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
        ),
    ]
