# Generated by Django 2.2.14 on 2020-07-17 17:27

from django.db import migrations
from guardian.shortcuts import assign_perm


def convert_groups_to_permissions(apps, schema_editor):
    NamespaceModel = apps.get_model('galaxy', 'Namespace')
    for namespace in NamespaceModel.objects.all():
        for group in namespace.groups.all():
            assign_perm('galaxy.change_namespace', group, namespace)
            assign_perm('galaxy.view_namespace', group, namespace)


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_inbound_repo_per_namespace'),
    ]

    operations = [
        migrations.RunPython(convert_groups_to_permissions),
        migrations.RemoveField(
            model_name='namespace',
            name='groups',
        ),
    ]
