# Generated by Django 2.2.15 on 2020-08-25 14:39

from django.db import models
from django.db import migrations
import django_lifecycle.mixins
import galaxy_ng.app.access_control.mixins
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0021_rename_role_remote'),
        ('galaxy', '0004_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRemoteProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'default_related_name': '%(app_label)s_%(model_name)s',
                'indexes': [],
                'constraints': [],
            },
            bases=('ansible.collectionremote', django_lifecycle.mixins.LifecycleModelMixin, models.Model, galaxy_ng.app.access_control.mixins.GroupModelPermissionsMixin, pulpcore.app.models.access_policy.AutoDeleteObjPermsMixin),
        ),
    ]
