# Generated by Django 2.2.14 on 2020-07-24 12:48

from django.db import migrations

from guardian.shortcuts import assign_perm


def convert_groups_to_permissions(apps, schema_editor):
    SyncListModel = apps.get_model('galaxy', 'SyncList')
    for synclist in SyncListModel.objects.all():
        for group in synclist.groups.all():
            assign_perm('galaxy.change_synclist', group, synclist)
            assign_perm('galaxy.view_synclist', group, synclist)

class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0004_remove_namespace_groups'),
    ]

    operations = [
        migrations.RunPython(convert_groups_to_permissions),
        migrations.RemoveField(
            model_name='synclist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='synclist',
            name='users',
        ),
    ]
