# Generated by Django 2.2.14 on 2020-07-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0005_remove_synclist_groups_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namespace',
            options={'permissions': (('upload_to_namespace', 'Upload collections to namespace'),)},
        ),
    ]
