# Generated by Django 2.2.19 on 2021-03-26 20:45

from django.db import migrations
import django_lifecycle.mixins
import galaxy_ng.app.access_control.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0018_containerdistribution_description'),
        ('galaxy', '0018_pulp_container_access_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerNamespace',
            fields=[
            ],
            options={
                'proxy': True,
                'default_related_name': '%(app_label)s_%(model_name)s',
                'indexes': [],
                'constraints': [],
            },
            bases=('container.containernamespace', django_lifecycle.mixins.LifecycleModelMixin, galaxy_ng.app.access_control.mixins.GroupModelPermissionsMixin),
        ),
    ]
