# Generated by Django 3.2.6 on 2021-09-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rbaccontentguard'),
        ('galaxy', '0023_auto_20210903_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDownloadContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='galaxy_collectiondownloadcontentguard', serialize=False, to='core.contentguard')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard',),
        ),
    ]
