# Generated by Django 3.2.13 on 2022-05-04 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_distros(apps, schema_editor):
    SyncList = apps.get_model('galaxy', 'SyncList')
    AnsibleDistribution = apps.get_model('ansible', 'AnsibleDistribution')
    db_alias = schema_editor.connection.alias

    # Get "published" distro to add as default value
    distro_name = settings.get('GALAXY_API_DEFAULT_DISTRIBUTION_BASE_PATH', 'published')
    distro = AnsibleDistribution.objects.using(db_alias).get(name=distro_name)

    for synclist in SyncList.objects.using(db_alias).all():
        synclist.distribution = distro
        synclist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0041_alter_collectionversion_collection'),
        ('galaxy', '0027_delete_contentredirectcontentguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclist',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='ansible.ansibledistribution'),
        ),
        migrations.RunPython(code=set_default_distros),
        migrations.AlterField(
            model_name='synclist',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='ansible.ansibledistribution'),
        ),
        migrations.AlterField(
            model_name='synclist',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='ansible.ansiblerepository'),
        ),
        migrations.AlterField(
            model_name='synclist',
            name='upstream_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream_repositories', to='ansible.ansiblerepository'),
        ),
    ]
