# Generated by Django 3.2.15 on 2022-09-08 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0030_update_collection_remote_rhcertified_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('avatar_url', models.URLField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('namespace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='namespace', to='galaxy.namespace')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('full_metadata', models.JSONField(default=dict)),
                ('namespace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='galaxy.legacynamespace')),
            ],
        ),
    ]
