# Generated by Django 3.2.16 on 2022-11-04 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0032_add_validated_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_secret', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_setting', 'Can edit setting'),),
                'unique_together': {('key', 'version')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
