# Generated by Django 3.2.16 on 2023-01-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0033_dynamic_config_table'),
        ('galaxy', '0033_update_validated_repo'),
    ]

    operations = [
    ]
