# Generated by Django 3.2.18 on 2023-02-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0034_aiindexdenylist'),
        ('galaxy', '0034_remove_inbound_repos'),
    ]

    operations = [
    ]
