# Generated by Django 3.2.16 on 2023-01-19 20:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0034_merge_20230119_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(?!\\d)[a-zA-Z0-9_]+$', 'alphanumeric, no spaces, no hyphen, only underscore cant start with a number.')]),
        ),
    ]
