# Generated by Django 3.2.18 on 2023-02-15 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0034_remove_inbound_repos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIndexDenyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('namespace', 'Namespace'), ('legacy_namespace', 'Legacy Namespace')], max_length=255)),
                ('reference', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', message='Reference must be a valid namespace name.')])),
            ],
            options={
                'unique_together': {('scope', 'reference')},
            },
        ),
    ]
