# Generated by Django 4.2.1 on 2023-05-31 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_alter_artifactdistribution_distribution_ptr_and_more"),
        ("galaxy", "0040_fix_collection_remote_pulp_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistryremote",
            name="remote_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.remote",
            ),
        ),
    ]
