# Generated by Django 4.2.6 on 2023-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galaxy", "0042_namespace_created_namespace_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyRoleTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="legacyrole",
            name="tags",
            field=models.ManyToManyField(
                editable=False, related_name="legacyrole", to="galaxy.legacyroletag"
            ),
        ),
    ]
