# Generated by Django 4.2.7 on 2023-11-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_distribution_hidden"),
        ("galaxy", "0043_legacyroletag_legacyrole_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyRoleImport",
            fields=[
                (
                    "task",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="core.task",
                    ),
                ),
                ("messages", models.JSONField(default=list, editable=False)),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="galaxy.legacyrole",
                    ),
                ),
            ],
            options={
                "ordering": ["task__pulp_created"],
            },
        ),
    ]
