# Generated by Django 4.2.10 on 2024-02-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ansible", "0055_alter_collectionversion_version_alter_role_version"),
        ("galaxy", "0050_organization_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRepository",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galaxy.organization",
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ansible.ansiblerepository",
                    ),
                ),
            ],
        ),
    ]
