# Generated by Django 4.2.11 on 2024-04-09 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("galaxy", "0051_rename_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who created this resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="modified_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who last modified this resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who created this resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modified_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who last modified this resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
