# Generated by Django 4.2.15 on 2024-08-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galaxy", "0054_galaxy_role_defs_to_dab_defs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="users",
        ),
        migrations.RemoveField(
            model_name="team",
            name="users",
        ),
    ]
