---
- hosts: localhost
  tasks:
    - name: Get Keycloak Admin Token
      uri:
        url: "http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          username: admin
          password: admin
          grant_type: password
          client_id: admin-cli
      register: keycloak_token

    - name: Find User ID for fry
      uri:
        url: "http://localhost:8080/auth/admin/realms/aap/users?username=fry"
        method: GET
        headers:
          Authorization: "Bearer {{ keycloak_token.json.access_token }}"
          Content-Type: application/json
      register: user_search

    - name: Reset User Password
      uri:
        url: "http://localhost:8080/auth/admin/realms/aap/users/{{ user_search.json[0].id }}/reset-password"
        method: PUT
        body_format: json
        body:
          type: password
          value: "PlanetExpress2025!"
          temporary: false
        headers:
          Authorization: "Bearer {{ keycloak_token.json.access_token }}"
          Content-Type: application/json
        status_code: 204
      register: password_reset_result
      when: user_search.json | length > 0

    - name: Debug Password Reset
      debug:
        var: password_reset_result
