#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github galaxy_ng' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -euv

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

export PULP_URL="${PULP_URL:-http://pulp}"

export REPORTED_VERSION=$(http $PULP_URL/pulp/api/v3/status/ | jq --arg plugin galaxy --arg legacy_plugin galaxy_ng -r '.versions[] | select(.component == $plugin or .component == $legacy_plugin) | .version')
export DESCRIPTION="$(git describe --all --exact-match `git rev-parse HEAD`)"
if [[ $DESCRIPTION == 'tags/'$REPORTED_VERSION ]]; then
  export VERSION=${REPORTED_VERSION}
else
  export EPOCH="$(date +%s)"
  export VERSION=${REPORTED_VERSION}${EPOCH}
fi

export response=$(curl --write-out %{http_code} --silent --output /dev/null https://rubygems.org/gems/galaxy_ng_client/versions/$VERSION)

if [ "$response" == "200" ];
then
  echo "galaxy_ng client $VERSION has already been released. Installing from RubyGems.org."
  gem install galaxy_ng_client -v $VERSION
  touch galaxy_ng_client-$VERSION.gem
  tar cvf ruby-client.tar ./galaxy_ng_client-$VERSION.gem
  exit
fi

cd ../pulp-openapi-generator
rm -rf galaxy_ng-client
./generate.sh galaxy_ng ruby $VERSION
cd galaxy_ng-client
gem build galaxy_ng_client
gem install --both ./galaxy_ng_client-$VERSION.gem
tar cvf ../../galaxy_ng/ruby-client.tar ./galaxy_ng_client-$VERSION.gem
