x-common-env: &common-env

  GNUPGHOME: /root/.gnupg/

  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: admin

  POSTGRES_USER: galaxy_ng
  POSTGRES_PASSWORD: galaxy_ng
  POSTGRES_DB: galaxy_ng

  # no spying
  PULP_ANALYTICS: 'false'

  # normally goes into settings.py ...
  PULP_DATABASES__default__ENGINE: django.db.backends.postgresql
  PULP_DATABASES__default__NAME: galaxy_ng
  PULP_DATABASES__default__USER: galaxy_ng
  PULP_DATABASES__default__PASSWORD: galaxy_ng
  PULP_DATABASES__default__HOST: postgres
  PULP_DATABASES__default__PORT: 5432

  PULP_DEBUG: 1
  PULP_GALAXY_DEPLOYMENT_MODE: 'standalone'
  PULP_DEFAULT_FILE_STORAGE: "pulpcore.app.models.storage.FileSystem"
  PULP_REDIRECT_TO_OBJECT_STORAGE: 'false'

  # Hostname and prefix has to be correct
  PULP_GALAXY_API_PATH_PREFIX: '/api/galaxy/'
  PULP_CONTENT_PATH_PREFIX: '/pulp/content/'
  PULP_ANSIBLE_API_HOSTNAME: 'https://localhost'
  PULP_ANSIBLE_CONTENT_HOSTNAME: "https://localhost"
  PULP_CONTENT_ORIGIN: "https://localhost"
  PULP_CSRF_TRUSTED_ORIGINS: "['https://localhost']"

  # signing ...
  ENABLE_SIGNING: 0
  PULP_GALAXY_AUTO_SIGN_COLLECTIONS: 'false'
  PULP_GALAXY_REQUIRE_CONTENT_APPROVAL: 'true'
  PULP_GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: 'false'
  PULP_GALAXY_COLLECTION_SIGNING_SERVICE: 'ansible-default'
  PULP_GALAXY_CONTAINER_SIGNING_SERVICE: 'container-default'

  # pulp container ...
  PULP_TOKEN_AUTH_DISABLED: 'false'
  PULP_TOKEN_SERVER: 'https://localhost/token/'
  PULP_TOKEN_SIGNATURE_ALGORITHM: 'ES256'
  PULP_PUBLIC_KEY_PATH: '/src/galaxy_ng/dev/common/container_auth_public_key.pem'
  PULP_PRIVATE_KEY_PATH: '/src/galaxy_ng/dev/common/container_auth_private_key.pem'

  # auth ...
  PULP_GALAXY_AUTHENTICATION_CLASSES: "['galaxy_ng.app.auth.session.SessionAuthentication', 'ansible_base.jwt_consumer.hub.auth.HubJWTAuth', 'rest_framework.authentication.TokenAuthentication', 'rest_framework.authentication.BasicAuthentication']"
  PULP_ANSIBLE_BASE_JWT_VALIDATE_CERT: 'false'
  PULP_ANSIBLE_BASE_JWT_KEY: 'https://localhost'
  PULP_GALAXY_FEATURE_FLAGS__external_authentication: 'true'

  # disable user/group modifications
  PULP_ALLOW_LOCAL_RESOURCE_MANAGEMENT: 'false'

  # role content workaround ..
  PULP_ANSIBLE_BASE_ROLES_REQUIRE_VIEW: 'false'

  # DEV EDITABLE STUFF
  LOCK_REQUIREMENTS: 0
  DEV_SOURCE_PATH: "galaxy_ng"
  # To enable editable installs of local checkouts change the variable above keeping the ordering as follows:
  # DEV_SOURCE_PATH: "dynaconf:pulpcore:galaxy_importer:pulp_ansible:pulp_container:galaxy_ng:django-ansible-base"


services:
  base_img:
    build:
      context: ..
      dockerfile: Dockerfile
    image: "localhost/galaxy_ng/galaxy_ng:base"

  redis:
    image: "redis:5"

  postgres:
    image: "postgres:13"
    environment:
      <<: *common-env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "galaxy_ng"]
      interval: 10s
      retries: 5

  helper:  # should this be moved to a custom Dockerfile?
    image: quay.io/centos/centos:stream9
    environment:
      <<: *common-env
    depends_on:
      - postgres
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    command: |
      bash -c "
        echo 'Moving required files to the required places.';

        # Workarounds - Pulp SigningService can't access envvars;
        /src/galaxy_ng/dev/compose/signing/setup_gpg_workarounds.sh;
        cat /etc/pulp/certs/GNUPGHOME.workaround.txt;
        cat /etc/pulp/certs/HOME.workaround.txt;

        # Keys;
        cp /src/galaxy_ng/dev/compose/database/database_fields.symmetric.key /etc/pulp/certs/database_fields.symmetric.key;
        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key /etc/pulp/certs/signing-secret.key
        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key.password.txt /etc/pulp/certs/signing-secret.key.password.txt
        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key /etc/pulp/certs/signing-public.key
        find /etc/pulp/certs;

        # Scripts;
        cp /src/galaxy_ng/dev/compose/signing/collection_sign.sh /var/lib/pulp/scripts/collection_sign.sh;
        cp /src/galaxy_ng/dev/compose/signing/container_sign.sh /var/lib/pulp/scripts/container_sign.sh;
        chmod +x /var/lib/pulp/scripts/*_sign.sh;
        find /var/lib/pulp/scripts;

        echo 'DONE!';
      "

  migrations:
    image: "localhost/galaxy_ng/galaxy_ng:base"
    depends_on:
      - base_img
      - postgres
      - helper
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    environment:
      <<: *common-env
    user: root
    command: |
      bash -c "
        set -e;
        rm -rf /var/lib/pulp/.migrated;
        while [[ ! -f /etc/pulp/certs/database_fields.symmetric.key ]]; do
          echo 'Waiting for key';
          sleep 2;
        done;
        /src/galaxy_ng/dev/compose/bin/devinstall;
        pulpcore-manager check --database default;
        pulpcore-manager migrate;
        pulpcore-manager shell < /src/galaxy_ng/dev/common/setup_test_data.py;
        pulpcore-manager createsuperuser --noinput || true;
        touch /var/lib/pulp/.migrated;
      "

  api:
    image: "localhost/galaxy_ng/galaxy_ng:base"
    depends_on:
      - base_img
      - postgres
      - helper
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: root
    command: |
      bash -c "
        while [[ ! -f /var/lib/pulp/.migrated ]]; do
          echo 'Waiting for migrations ...';
          sleep 2;
        done;

        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-api
      "

  content:
    image: "localhost/galaxy_ng/galaxy_ng:base"
    depends_on:
      - base_img
      - postgres
      - helper
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: root
    command: |
      bash -c "
        while [[ ! -f /var/lib/pulp/.migrated ]]; do
          echo 'Waiting for migrations ...';
          sleep 2;
        done;

        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-content
      "

  worker:
    image: "localhost/galaxy_ng/galaxy_ng:base"
    depends_on:
      - base_img
      - postgres
      - helper
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    environment:
      <<: *common-env
    user: root
    command: |
      bash -c "
        while [[ ! -f /var/lib/pulp/.migrated ]]; do
          echo 'Waiting for migrations ...';
          sleep 2;
        done;
        while [[ ! -f /etc/pulp/certs/signing-secret.key ]]; do
          echo 'Waiting for signing key';
          sleep 2;
        done;

        # Worker needs gpg in order to consume signing tasks;
        /src/galaxy_ng/dev/compose/signing/setup_gpg_keys.sh;
        gpg --list-secret-keys;

        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-worker
      "

  manager:
    image: "localhost/galaxy_ng/galaxy_ng:base"
    depends_on:
      - base_img
      - postgres
      - helper
      - migrations
      - worker
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
    environment:
      <<: *common-env
    user: root
    command: |
      bash -c "
        while [[ ! -f /var/lib/pulp/.migrated ]]; do
          echo 'Waiting for migrations ...';
          sleep 2;
        done;
        while [[ ! -f /etc/pulp/certs/signing-secret.key ]]; do
          echo 'Waiting for signing key';
          sleep 2;
        done;

        /src/galaxy_ng/dev/compose/bin/devinstall;

        # Schedule resource sync;
        pulpcore-manager task-scheduler --id dab_sync --interval 15 --path "galaxy_ng.app.tasks.resource_sync.run";
        curl -s -u admin:admin http://api:24817/api/galaxy/pulp/api/v3/task-schedules/?name=dab_sync | python -m json.tool;

        # Keys are needed to register signing services;
        /src/galaxy_ng/dev/compose/signing/setup_gpg_keys.sh;
        gpg --list-secret-keys;

        # Setup signing services;
        /src/galaxy_ng/dev/compose/signing/setup_signing_services.sh;
        curl -s -u admin:admin http://api:24817/api/galaxy/pulp/api/v3/signing-services/?fields=name,script,pubkey_fingerprint | python -m json.tool;

        # Setup repository gpgkey for upload verification;
        /src/galaxy_ng/dev/compose/signing/setup_repo_keyring.sh

        # Dev tools; SHOULD THIS MOVE TO A CUSTOM Dockerfile?
        /venv/bin/pip3.11 install ipython ipdb django-extensions;

        echo ' ';
        echo '###################### API ROOT ##############################';
        curl -s http://api:24817/api/galaxy/ | python -m json.tool;

        echo '######################## READY ###############################';
        echo ' ';
        echo 'API: http://localhost:5001/api/galaxy/v3/swagger-ui/';
        echo 'Django Admin CLI: docker compose -f aap_compose_dev.yaml exec manager pulpcore-manager';
        echo 'Settings list: docker compose -f aap_compose_dev.yaml exec manager dynaconf list';

        # Keep it running indefinitely to enable `docker compose -f ... exec manager /bin/bash`
        tail -f /dev/null
      "

  nginx:
    image: "nginx:latest"
    depends_on:
      - base_img
      - postgres
      - helper
      - migrations
      - api
      - content
    ports:
      - '5001:5001'
    volumes:
      - '../nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

volumes:
  var_lib_pulp:
    name: var_lib_pulp
  etc_pulp_certs:
    name: etc_pulp_certs

networks:
  service-mesh:
    name: service-mesh
