# This Dockerfile is meant to extend the main Dockerfile
# Moving files to the required places
# Installing extra development libraries and tools
FROM localhost/galaxy_ng/galaxy_ng:base

ARG GNUPGHOME
ENV GNUPGHOME $GNUPGHOME

USER root
RUN LANG=C dnf -y --disableplugin=subscription-manager install nc

USER galaxy
RUN ${VIRTUAL_ENV}/bin/python3 -m pip install debugpy hupper ipython ipdb rpdb django-extensions pulp-cli

RUN /app/dev/compose/signing/setup_gpg_workarounds.sh

COPY --chown=galaxy:galaxy database/database_fields.symmetric.key /etc/pulp/certs/database_fields.symmetric.key
COPY --chown=galaxy:galaxy signing/keys /etc/pulp/certs/
COPY --chown=galaxy:galaxy signing/scripts /var/lib/pulp/scripts/

RUN set -ex; \
    chmod -R 0775 /etc/pulp/certs /var/lib/pulp/scripts && \
    /app/dev/compose/signing/setup_gpg_keys.sh
