x-common-env: &common-env

  GNUPGHOME: /etc/pulp/gnupg/
  GALAXY_IMPORTER_CONFIG: /src/galaxy_ng/profiles/insights/galaxy-importer/galaxy-importer.cfg

  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: admin

  POSTGRES_USER: galaxy_ng
  POSTGRES_PASSWORD: galaxy_ng
  POSTGRES_DB: galaxy_ng

  PULP_CACHE_ENABLED: 'true'
  PULP_REDIS_HOST: redis
  REDIS_SERVICE_HOST: redis
  PULP_REDIS_PORT: 6379
  PULP_REDIS_PASSWORD: ""

  # no spying
  PULP_ANALYTICS: 'false'

  # normally goes into settings.py ...
  PULP_DATABASES__default__ENGINE: django.db.backends.postgresql
  PULP_DATABASES__default__NAME: galaxy_ng
  PULP_DATABASES__default__USER: galaxy_ng
  PULP_DATABASES__default__PASSWORD: galaxy_ng
  PULP_DATABASES__default__HOST: postgres
  PULP_DATABASES__default__PORT: 5432

  PULP_DEBUG: 1
  PULP_GALAXY_DEPLOYMENT_MODE: 'insights'
  PULP_RH_ENTITLEMENT_REQUIRED: 'insights'
  PULP_DEFAULT_FILE_STORAGE: "pulpcore.app.models.storage.FileSystem"
  PULP_REDIRECT_TO_OBJECT_STORAGE: 'false'

  # collection download
  PULP_X_PULP_CONTENT_HOST: content
  PULP_X_PULP_CONTENT_PORT: 24816

  # Hostname and prefix has to be correct
  PULP_GALAXY_API_PATH_PREFIX: '/api/automation-hub/'
  PULP_CONTENT_PATH_PREFIX: '/api/automation-hub/pulp/content/'
  PULP_ANSIBLE_API_HOSTNAME: 'http://localhost:8080'
  PULP_ANSIBLE_CONTENT_HOSTNAME: "http://localhost:8080"
  PULP_CONTENT_ORIGIN: "http://localhost:8080"
  PULP_CSRF_TRUSTED_ORIGINS: "['https://localhost']"



  # auth ...
  PULP_GALAXY_AUTHENTICATION_CLASSES: "['galaxy_ng.app.auth.auth.RHIdentityAuthentication']"

  PULP_GALAXY_FEATURE_FLAGS__dab_resource_registry: 'false'
  PULP_GALAXY_REQUIRE_CONTENT_APPROVAL: 'true'
  PULP_GALAXY_AUTO_SIGN_COLLECTIONS: 'false'
  PULP_GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: 'false'
  GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: 'false'
  ENABLE_COLLECTION_SIGNING: 0

  # Resource server
  # This disables the attempt for resource syncing
  PULP_RESOURCE_SERVER_SYNC_ENABLED: 'false'
  # Set above to 'true' if/when RESOURCE_SERVER is configured
  # The next variables must be configured to enable resource sync
  # PULP_RESOURCE_SERVER__URL='https://localhost'
  # PULP_RESOURCE_SERVER__SECRET_KEY='?'
  # PULP_RESOURCE_SERVER__VALIDATE_HTTPS='false'

  # Integration test settings
  HUB_AUTH_URL: 'http://localhost:8080/auth/realms/redhat-external/protocol/openid-connect/token'
  HUB_API_ROOT: 'http://localhost:8080/api/automation-hub/'
  HUB_USE_MOVE_ENDPOINT: "true"


  HUB_LOCAL: 0
  HUB_TEST_MARKS: deployment_cloud or all

  # Unpin dependencies on setup.py if set to 0
  LOCK_REQUIREMENTS: 0

  # DEV EDITABLE STUFF
  # To enable editable to install local checkouts set DEV_SOURCE_PATH keeping the ordering as follows:
  # "dynaconf:pulpcore:galaxy_importer:pulp_ansible:pulp_container:galaxy_ng:django-ansible-base"
  # This can be done as part of the `docker compose` call:
  # $ DEV_SOURCE_PATH="pulp_container:galaxy_ng" docker compose -f dev/compose/insights.yaml up
  DEV_SOURCE_PATH:
  # To enable vscode debug
  # $ ENABLE_DEBUGPY=1
  ENABLE_DEBUGPY:

# allow attaching to the running container
x-debugging: &debugging
  stdin_open: true
  tty: true

services:
  base_img:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        USER_ID: "${USER_ID:-1000}"
    image: "localhost/galaxy_ng/galaxy_ng:base"

  base_img_dev:  # Extends base_img with extra files and dev tools
    depends_on:
      - base_img
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        <<: *common-env
    image: "localhost/galaxy_ng/galaxy_ng:dev"

  proxy:
    build:
      context: "../../profiles/insights/proxy"
    ports:
      - "8080:8080"
    environment:
      UPSTREAM_URL: "http://api:8000"
      PROXY_PORT: "8080"
    volumes:
      - "../../profiles/insights/proxy:/app:ro,Z"

  redis:
    image: "redis:5"
    environment:
      <<: *common-env
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: "postgres:13"
    ports:
      - '5433:5432'
    environment:
      <<: *common-env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "galaxy_ng"]
      interval: 10s
      retries: 5
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    # Uncomment below to spam out every DB statement to the service stderr
    # WARNING: enabling log_statement=all makes database slower
    # command: ["postgres", "-c", "log_statement=ddl", "-c", "log_destination=stderr"]

  migrations:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      base_img_dev:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    user: root
    <<: *debugging
    command: |
      bash -c "
        set -e;
        rm -rf /var/lib/pulp/.migrated;
        /src/galaxy_ng/dev/compose/bin/devinstall;

        pulpcore-manager check --database default;
        pulpcore-manager migrate;
        pulpcore-manager shell < /src/galaxy_ng/dev/common/setup_test_data.py;
        pulpcore-manager createsuperuser --noinput || true;

        touch /var/lib/pulp/.migrated;
        chown -R galaxy:galaxy /etc/pulp /var/lib/pulp;
      "

  api:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      base_img_dev:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    ports:
      - '5677:5677'
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;
        /src/galaxy_ng/dev/compose/bin/reloader start-api
      "
    healthcheck:
      test: readyz.py $${PULP_GALAXY_API_PATH_PREFIX}pulp/api/v3/status/
      interval: 10s
      timeout: 5s
      retries: 5

  content:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      base_img_dev:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    ports:
      - '5678:5678'
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;
        /src/galaxy_ng/dev/compose/bin/reloader start-content-app
      "
    healthcheck:
      test: readyz.py $${PULP_CONTENT_PATH_PREFIX}
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    deploy:
      replicas: 1
    depends_on:
      base_img_dev:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    ports:
      - '5679:5679'
    environment:
      <<: *common-env
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        # Worker needs gpg in order to consume signing tasks;
        gpg --list-secret-keys;

        ENTRYPOINT=/venv/bin/pulpcore-worker /src/galaxy_ng/dev/compose/bin/reloader start-worker
      "

  manager:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      base_img_dev:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      api:
        condition: service_healthy
      content:
        condition: service_healthy
      worker:
        condition: service_started
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        # Give some time for API to start;
        sleep 5;

        # Set pulp CLI
        pulp config create --overwrite --base-url http://api:8000 --api-root $${PULP_GALAXY_API_PATH_PREFIX}pulp/ --username $$DJANGO_SUPERUSER_USERNAME --password $$DJANGO_SUPERUSER_PASSWORD --no-verify-ssl

        # Setup repository gpgkey for upload verification;
        /src/galaxy_ng/dev/compose/signing/setup_repo_keyring.sh;

        echo ' ';
        echo '###################### API ROOT ##############################';
        curl -s -k -u org-admin:redhat http://proxy:8080/api/automation-hub/ | python -m json.tool;
        echo '################### DEV_SOURCE_PATH ##########################';
        echo $$DEV_SOURCE_PATH;
        echo ' ';
        echo '######################## READY ###############################';
        echo ' ';
        echo 'Credentials:  org-admin:redhat OR jdoe:redhat';
        echo 'API Spec:      http://localhost:5001/api/automation-hub/v3/swagger-ui/';
        echo 'API Spec proxy:http://localhost:8080/api/automation-hub/v3/swagger-ui/';
        echo 'Django Admin:  docker compose -f dev/compose/aap.yaml exec manager pulpcore-manager';
        echo 'Settings list: docker compose -f dev/compose/aap.yaml exec manager dynaconf list';
        echo 'Docs:          https://github.com/ansible/galaxy_ng/blob/master/dev/compose/README.md';
        echo '##############################################################';

        # Keep it running indefinitely to enable `docker compose -f ... exec manager /bin/bash`;
        tail -f /dev/null
      "

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      base_img:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      api:
        condition: service_healthy
      content:
        condition: service_healthy
    ports:
      - '5001:5001'
    volumes:
      - '../nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z'

volumes:
  var_lib_pulp:
    name: var_lib_pulp
  etc_pulp_certs:
    name: etc_pulp_certs
  redis_data:
    name: redis_data
  pg_data:
    name: pg_data

networks:
  service-mesh:
    name: service-mesh
