x-common-env: &common-env

  GNUPGHOME: /etc/pulp/gnupg/

  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: admin

  POSTGRES_USER: galaxy_ng
  POSTGRES_PASSWORD: galaxy_ng
  POSTGRES_DB: galaxy_ng

  # no spying
  PULP_ANALYTICS: 'false'

  # normally goes into settings.py ...
  PULP_DATABASES__default__ENGINE: django.db.backends.postgresql
  PULP_DATABASES__default__NAME: galaxy_ng
  PULP_DATABASES__default__USER: galaxy_ng
  PULP_DATABASES__default__PASSWORD: galaxy_ng
  PULP_DATABASES__default__HOST: postgres
  PULP_DATABASES__default__PORT: 5432

  PULP_DEBUG: 1
  PULP_GALAXY_DEPLOYMENT_MODE: standalone
  PULP_DEFAULT_FILE_STORAGE: "pulpcore.app.models.storage.FileSystem"
  PULP_REDIRECT_TO_OBJECT_STORAGE: 'false'

  # Hostname and prefix has to be correct
  PULP_GALAXY_API_PATH_PREFIX: '/api/'
  PULP_CONTENT_PATH_PREFIX: '/pulp/content/'
  PULP_ANSIBLE_API_HOSTNAME: 'http://localhost:5001'
  PULP_ANSIBLE_CONTENT_HOSTNAME: "http://localhost:5001"
  PULP_CONTENT_ORIGIN: "http://localhost:5001"
  PULP_CSRF_TRUSTED_ORIGINS: "['https://localhost']"

  # signing ...
  PULP_GALAXY_AUTO_SIGN_COLLECTIONS: 'false'
  PULP_GALAXY_REQUIRE_CONTENT_APPROVAL: 'false'
  PULP_GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: 'false'
  PULP_GALAXY_COLLECTION_SIGNING_SERVICE: 'ansible-default'
  PULP_GALAXY_CONTAINER_SIGNING_SERVICE: 'container-default'

  # pulp container ...
  PULP_TOKEN_AUTH_DISABLED: false
  PULP_TOKEN_SERVER: 'http://localhost:5001/token/'
  PULP_TOKEN_SIGNATURE_ALGORITHM: ES256
  PULP_PUBLIC_KEY_PATH: '/src/galaxy_ng/dev/common/container_auth_public_key.pem'
  PULP_PRIVATE_KEY_PATH: '/src/galaxy_ng/dev/common/container_auth_private_key.pem'
  SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: 'http://localhost:8080/auth/realms/master/protocol/openid-connect/token'

  PULP_SOCIAL_AUTH_KEYCLOAK_KEY: automation-hub
  PULP_SOCIAL_AUTH_KEYCLOAK_SECRET: REALLYWELLKEPTSECRET
  PULP_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: "CHANGE-ME"
  PULP_SOCIAL_AUTH_LOGIN_REDIRECT_URL: 'http://localhost:5001'
  PULP_KEYCLOAK_PROTOCOL: http
  PULP_KEYCLOAK_HOST: keycloak
  PULP_KEYCLOAK_HOST_LOOPBACK: localhost
  PULP_KEYCLOAK_PORT: 8080
  PULP_KEYCLOAK_REALM: aap
  PULP_RH_ENTITLEMENT_REQUIRED: insights

  HUB_API_ROOT: 'http://localhost:5001/api/galaxy'
  HUB_USE_MOVE_ENDPOINT: 'true'
  CONTAINER_REGISTRY: 'localhost:5001'

  # Unpin dependencies on setup.py if set to 0
  LOCK_REQUIREMENTS: 0

  # DEV EDITABLE STUFF
  # To enable editable installs of local checkouts set DEV_SOURCE_PATH keeping the ordering as follows:
  # "dynaconf:pulpcore:galaxy_importer:pulp_ansible:pulp_container:galaxy_ng:django-ansible-base"
  # This can be done as part of the `docker compose` call:
  # $ DEV_SOURCE_PATH="pulp_container:galaxy_ng" docker compose -f dev/compose/standalone.yaml up
  DEV_SOURCE_PATH:

  PULP_AUTHENTICATION_BACKEND_PRESET: keycloak
  PULP_AUTH_LDAP_SERVER_URI: "ldap://ldap:10389"
  PULP_AUTH_LDAP_BIND_DN: "cn=admin,dc=planetexpress,dc=com"
  PULP_AUTH_LDAP_BIND_PASSWORD: "GoodNewsEveryone"
  PULP_AUTH_LDAP_USER_SEARCH_BASE_DN: "ou=people,dc=planetexpress,dc=com"
  PULP_AUTH_LDAP_USER_SEARCH_SCOPE: SUBTREE
  PULP_AUTH_LDAP_USER_SEARCH_FILTER: "(uid=%(user)s)"
  PULP_AUTH_LDAP_GROUP_SEARCH_BASE_DN: "ou=people,dc=planetexpress,dc=com"
  PULP_AUTH_LDAP_GROUP_SEARCH_SCOPE: SUBTREE
  PULP_AUTH_LDAP_GROUP_SEARCH_FILTER: "(objectClass=Group)"
  PULP_AUTH_LDAP_GROUP_TYPE_CLASS: "django_auth_ldap.config:GroupOfNamesType"
  PULP_AUTH_LDAP_ALWAYS_UPDATE_USER: true
  PULP_AUTH_LDAP_USER_ATTR_MAP__first_name: givenName
  PULP_AUTH_LDAP_USER_ATTR_MAP__last_name: sn
  PULP_AUTH_LDAP_USER_ATTR_MAP__email: mail
  PULP_AUTH_LDAP_MIRROR_GROUPS: true
  PULP_AUTH_LDAP_USER_FLAGS_BY_GROUP__is_staff: "cn=ship_crew,ou=people,dc=planetexpress,dc=com"
  PULP_AUTH_LDAP_USER_FLAGS_BY_GROUP__is_superuser: "cn=admin_staff,ou=people,dc=planetexpress,dc=com"
  PULP_GALAXY_LDAP_LOGGING: true

  PULP_GALAXY_AUTHENTICATION_CLASSES: "['galaxy_ng.app.auth.keycloak.KeycloakBasicAuth']"
  KEYCLOAK_REDIRECT_URL: "http://localhost:5001/"

  HUB_TEST_AUTHENTICATION_BACKEND: "keycloak"
  HUB_TEST_MARKS: "deployment_standalone or all or keycloak"

  PULP_RESOURCE_SERVER_SYNC_ENABLED: false

  API_PROTOCOL: http
  API_HOST: localhost
  API_PORT: 5001

  LDAP_LOGLEVEL: 256

x-debugging: &debugging
  stdin_open: true
  tty: true

services:
  base_img:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        USER_ID: "${USER_ID:-1000}"
    image: "localhost/galaxy_ng/galaxy_ng:base"

  base_img_dev:  # Extends base_img with extra files and dev tools
    depends_on:
      - base_img
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        <<: *common-env
    image: "localhost/galaxy_ng/galaxy_ng:dev"

  base_img_nginx:  # Extracts nginx files from base_img
    depends_on:
      - base_img
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: "localhost/galaxy_ng/galaxy_ng:nginx"

  redis:
    image: "redis:5"

  postgres:
    image: "postgres:13"
    ports:
      - '5433:5432'
    environment:
      <<: *common-env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "galaxy_ng"]
      interval: 10s
      retries: 5
    # Uncomment below to spam out every DB statement to the service stderr
    # WARNING: enabling log_statement=all makes database slower
    # command: ["postgres", "-c", "log_statement=ddl", "-c", "log_destination=stderr"]

  migrations:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      - base_img_dev
      - postgres
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    user: root
    <<: *debugging
    command: |
      bash -c "
        set -e;
        rm -rf /var/lib/pulp/.migrated;
        /src/galaxy_ng/dev/compose/bin/devinstall;

        pulpcore-manager check --database default;
        pulpcore-manager migrate;
        pulpcore-manager shell < /src/galaxy_ng/dev/common/setup_test_data.py;
        pulpcore-manager createsuperuser --noinput || true;

        touch /var/lib/pulp/.migrated;
        chown -R galaxy:galaxy /etc/pulp /var/lib/pulp;
      "

  api:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      - base_img_dev
      - postgres
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        /src/galaxy_ng/dev/compose/bin/reloader /src/galaxy_ng/dev/compose/bin/pulpcore-api
      "

  content:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      - base_img_dev
      - postgres
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    extra_hosts:
      localhost: "host-gateway"
    networks:
      - default
      - service-mesh
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        /src/galaxy_ng/dev/compose/bin/reloader /src/galaxy_ng/dev/compose/bin/pulpcore-content
      "

  worker:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      - base_img_dev
      - postgres
      - migrations
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        # Worker needs gpg in order to consume signing tasks;
        gpg --list-secret-keys;

        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-worker
      "

  manager:
    image: "localhost/galaxy_ng/galaxy_ng:dev"
    depends_on:
      - base_img_dev
      - postgres
      - migrations
      - worker
    volumes:
      - "etc_pulp_certs:/etc/pulp/certs"
      - "var_lib_pulp:/var/lib/pulp"
      - "../../../:/src"
      - "../../:/app"
    environment:
      <<: *common-env
    user: galaxy
    <<: *debugging
    command: |
      bash -c "
        /src/galaxy_ng/dev/compose/bin/devinstall;
        /src/galaxy_ng/dev/compose/bin/wait /var/lib/pulp/.migrated;

        # Give some time for API to start;
        sleep 5;

        # Setup signing services;
        gpg --list-secret-keys;
        /src/galaxy_ng/dev/compose/signing/setup_signing_services.sh;
        echo 'Signing Services';
        curl -s -u $$DJANGO_SUPERUSER_USERNAME:$$DJANGO_SUPERUSER_PASSWORD http://api:24817/api/galaxy/pulp/api/v3/signing-services/?fields=name,script,pubkey_fingerprint | python -m json.tool;

        # Setup repository gpgkey for upload verification;
        /src/galaxy_ng/dev/compose/signing/setup_repo_keyring.sh;

        echo ' ';
        echo '###################### API ROOT ##############################';
        curl -s -u $$DJANGO_SUPERUSER_USERNAME:$$DJANGO_SUPERUSER_PASSWORD http://api:24817/api/galaxy/ | python -m json.tool;
        echo '################### DEV_SOURCE_PATH ##########################';
        echo $$DEV_SOURCE_PATH;
        echo ' ';
        echo '######################## READY ###############################';
        echo ' ';
        echo 'Credentials:  ' $$DJANGO_SUPERUSER_USERNAME:$$DJANGO_SUPERUSER_PASSWORD;
        echo 'API Spec:      http://localhost:5001/api/galaxy/v3/swagger-ui/';
        echo 'Django Admin:  docker compose -f dev/compose/ldap.yaml exec manager pulpcore-manager';
        echo 'Settings list: docker compose -f dev/compose/ldap.yaml exec manager dynaconf list';
        echo 'Docs:          https://github.com/ansible/galaxy_ng/blob/master/dev/compose/README.md';
        echo '##############################################################';

        # Keep it running indefinitely to enable `docker compose -f ... exec manager /bin/bash`;
        tail -f /dev/null
      "

  nginx:
    image: "localhost/galaxy_ng/galaxy_ng:nginx"
    depends_on:
      - base_img_nginx
      - postgres
      - migrations
      - api
      - content
      - keycloak
    ports:
      - '5001:5001'
    volumes:
      - '../nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z'

  ldap:
    image: "rroemhild/test-openldap"
    environment:
      <<: *common-env
    ports:
      - "10389:10389"
      - "10636:10636"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  keycloak:
    image: "quay.io/keycloak/keycloak:legacy"
    environment:
      <<: *common-env
      DB_VENDOR: POSTGRES
      DB_ADDR: kc-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - kc-postgres
    volumes:
      - "./standalone-keycloak/keycloak.conf:/opt/jboss/keycloak/standalone/configuration/keycloak.conf:ro,Z"

  kc-postgres:
    image: "postgres:13"
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

volumes:
  var_lib_pulp:
    name: var_lib_pulp
  etc_pulp_certs:
    name: etc_pulp_certs
  kc_pg_data:
    name: kc_pg_data

networks:
  service-mesh:
    name: service-mesh
