---
- name: Galaxy + AH Collection Tests for Repo Automation
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - galaxy.galaxy

  pre_tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: vars.yml

  tasks:
    - name: Authenticate and retrieve API token
      ah_token:
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"

    - name: Configure community repository
      ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements:
          - community.docker
          - geerlingguy.k8s
        ah_host: "{{ ah_host }}"
        ah_token: "{{ ah_token }}"
        ah_path_prefix: "{{ ah_path_prefix }}"

    - name: Sync community repository
      ah_repository_sync:
        name: community
        ah_host: "{{ ah_host }}"
        ah_token: "{{ ah_token }}"
        ah_path_prefix: "{{ ah_path_prefix }}"

    - name: Deauthenticate
      ah_token:
        ah_host: "{{ ah_host }}"
        ah_token: "{{ ah_token }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
