---
version: "3.7"

services:
  api:
    env_file:
      - './standalone-ldap/galaxy_ng.env'
      - '../.compose.env'
  worker:
    env_file:
      - './standalone-ldap/galaxy_ng.env'
      - '../.compose.env'
  content-app:
    env_file:
      - './standalone-ldap/galaxy_ng.env'
      - '../.compose.env'
  ldap:
    image: "rroemhild/test-openldap"
    ports:
      - "10389:10389"
      - "10636:10636"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
