ci_base: pulp/pulp-ci-centos9
image:
  name: pulp
  tag: "ci_build"
plugins:
  - name: galaxy_ng
    path: "/src/galaxy_ng"
    source: "./galaxy_ng"
pulp_container_tag: "latest"
pulp_scheme: "https"

api_root: "/api/galaxy/pulp/"

services:
  - name: pulp
    image: "pulp:ci_build"
    volumes:
      - ./cache/settings:/etc/pulp
      - ../../../.:/src
      #- ../../.:/src/galaxy_ng
      #- ../../../pulp_ansible:/src/pulp_ansible
      #- ../../../pulpcore:/src/pulpcore
      #- ../../../pulp-openapi-generator:/src/pulp-openapi-generator
    env:
      PULP_WORKERS: "4"
      PULP_HTTPS: "true"

s3_test: False
gcp_test: False
azure_test: False

pulp_settings:
  RH_ENTITLEMENT_REQUIRED: "insights"
  GALAXY_REQUIRE_CONTENT_APPROVAL: False
  GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: False

