---
apiVersion: v1
kind: Template
metadata:
  name: automation-hub
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: galaxy-importer-config
    namespace: automation-hub
  data:
    galaxy-importer.cfg: |
      [galaxy-importer]
      LOG_LEVEL_MAIN = INFO
      RUN_ANSIBLE_TEST = True
      INFRA_PULP = True
      INFRA_OSD = True
      ANSIBLE_LOCAL_TMP = '/tmp/ansible'

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: automation-hub
    namespace: automation-hub
  spec:
    # The name of the ClowdEnvironment providing the services
    envName: ${ENV_NAME}

    deployments:
    - name: "backend${SUFFIX}"
      minReplicas: ${{NGINX_REPLICAS}}
      podSpec:
        name: backend
        image: ${NGINX_IMAGE}:${NGINX_IMAGE_TAG}
        resources:
          limits:
            cpu: ${{NGINX_CPU_LIMIT}}
            memory: ${{NGINX_MEMORY_LIMIT}}
          requests:
            cpu: ${{NGINX_CPU_REQUEST}}
            memory: ${{NGINX_MEMORY_REQUEST}}
        env:
          - name: LISTEN_PORT
            value: '8000'
          - name: GALAXY_API_HOST
            value: "automation-hub-galaxy-api${SUFFIX}"
          - name: GALAXY_API_PORT
            value: '8000'
        volumeMounts:
          - name: cache
            mountPath: /var/cache/nginx
        volumes:
          - name: cache
            emptyDir: {}
      webServices:
        public:
            enabled: true

    - name: "galaxy-api${SUFFIX}"
      minReplicas: ${{GALAXY_API_REPLICAS}}
      podSpec:
        name: galaxy-api
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'api']
        initContainers:
          - args: ["wait-for-migrations"]
            inheritEnv: true
        resources:
          limits:
            cpu: ${{GALAXY_API_CPU_LIMIT}}
            memory: ${{GALAXY_API_MEMORY_LIMIT}}
          requests:
            cpu: ${{GALAXY_API_CPU_REQUEST}}
            memory: ${{GALAXY_API_MEMORY_REQUEST}}
        env:
          - name: PULP_GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: ${{CONTENT_ORIGIN}}
          - name: PULP_RH_ENTITLEMENT_REQUIRED
            value: 'insights'
          - name: PULP_X_PULP_CONTENT_HOST
            value: 'automation-hub-pulp-content-app${SUFFIX}'
          - name: PULP_X_PULP_CONTENT_PORT
            value: '10000'
          - name: PULP_REDIS_SSL
            value: ${{REDIS_SSL}}
      webServices:
        public:
            enabled: true

    - name: "pulp-resource-manager${SUFFIX}"
      minReplicas: ${{PULP_RESOURCE_MANAGER_REPLICAS}}
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'resource-manager']
        initContainers:
          - args: ["manage", "migrate"]
            inheritEnv: true
        resources:
          limits:
            cpu: ${{PULP_RESOURCE_MANAGER_CPU_LIMIT}}
            memory: ${{PULP_RESOURCE_MANAGER_MEMORY_LIMIT}}
          requests:
            cpu: ${{PULP_RESOURCE_MANAGER_CPU_REQUEST}}
            memory: ${{PULP_RESOURCE_MANAGER_MEMORY_REQUEST}}
        env:
          - name: PULP_GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: ${{CONTENT_ORIGIN}}
          - name: PULP_REDIS_SSL
            value: ${{REDIS_SSL}}

    - name: "pulp-content-app${SUFFIX}"
      minReplicas: ${{PULP_CONTENT_APP_REPLICAS}}
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'content-app']
        initContainers:
          - args: ["wait-for-migrations"]
            inheritEnv: true
        resources:
          limits:
            cpu: ${{PULP_CONTENT_APP_CPU_LIMIT}}
            memory: ${{PULP_CONTENT_APP_MEMORY_LIMIT}}
          requests:
            cpu: ${{PULP_CONTENT_APP_CPU_REQUEST}}
            memory: ${{PULP_CONTENT_APP_MEMORY_REQUEST}}
        env:
          - name: PULP_GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: ${{CONTENT_ORIGIN}}
          - name: GUNICORN_PORT
            value: '10000'
          - name: PULP_REDIS_SSL
            value: ${{REDIS_SSL}}
      webServices:
        private:
            enabled: true

    - name: "pulp-worker${SUFFIX}"
      minReplicas: ${{PULP_WORKER_REPLICAS}}
      k8sAccessLevel: edit
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'worker']
        initContainers:
          - args: ["wait-for-migrations"]
            inheritEnv: true
        resources:
          limits:
            cpu: ${{PULP_WORKER_CPU_LIMIT}}
            memory: ${{PULP_WORKER_MEMORY_LIMIT}}
          requests:
            cpu: ${{PULP_WORKER_CPU_REQUEST}}
            memory: ${{PULP_WORKER_MEMORY_REQUEST}}
        env:
          - name: PULP_GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: ${{CONTENT_ORIGIN}}
          - name: IMPORTER_API_DOMAIN
            value: ${{API_DOMAIN}}
          - name: IMPORTER_JOB_NAMESPACE
            value: ${{IMPORTER_JOB_NAMESPACE}}
          - name: IMPORTER_MEMORY_REQUEST
            value: 1Gi
          - name: IMPORTER_MEMORY_LIMIT
            value: 2Gi
          - name: IMPORTER_CPU_REQUEST
            value: 500m
          - name: IMPORTER_CPU_LIMIT
            value: 1000m
          - name: PULP_REDIS_SSL
            value: ${{REDIS_SSL}}
        volumeMounts:
          - name: importer-config
            mountPath: /etc/galaxy-importer
        volumes:
          - name: importer-config
            configMap:
              name: galaxy-importer-config

    # Creates a database if local mode, or uses RDS in production
    database:
      # Must specify both a name and a major postgres version
      name: automation-hub
      version: 12

    inMemoryDb: true

    objectStore:
      - automation-hub

parameters:
- description: Clowder ENV
  name: ENV_NAME
  required: true
- name: SUFFIX
  value: ''

- descripton: Automation Hub image name
  name: IMAGE_NAME
  value: "quay.io/cloudservices/automation-hub-galaxy-ng"
- description: Automation Hub image tag
  name: IMAGE_TAG
  required: true

- name: NGINX_IMAGE
  value: "quay.io/cloudservices/automation-hub-nginx"
- name: NGINX_IMAGE_TAG
  value: latest

- name: IMPORTER_JOB_NAMESPACE
  required: true
- name: CONTENT_ORIGIN
  value: 'localhost'
- name: API_DOMAIN
  value: https://kubernetes.default.svc:443
- name: REDIS_SSL
  value: "false"

# nginx resource requirements
- name: NGINX_REPLICAS
  value: '1'
- name: NGINX_MEMORY_REQUEST
  value: 64Mi
- name: NGINX_MEMORY_LIMIT
  value: 128Mi
- name: NGINX_CPU_REQUEST
  value: 50m
- name: NGINX_CPU_LIMIT
  value: 200m

# galaxy-api resource requirements
- name: GALAXY_API_REPLICAS
  value: '1'
- name: GALAXY_API_MEMORY_REQUEST
  value: 1024Mi
- name: GALAXY_API_MEMORY_LIMIT
  value: 1024Mi
- name: GALAXY_API_CPU_REQUEST
  value: 200m
- name: GALAXY_API_CPU_LIMIT
  value: 600m

# pulp-resource-manager resource requirements
- name: PULP_RESOURCE_MANAGER_REPLICAS
  value: '1'
- name: PULP_RESOURCE_MANAGER_MEMORY_REQUEST
  value: 512Mi
- name: PULP_RESOURCE_MANAGER_MEMORY_LIMIT
  value: 512Mi
- name: PULP_RESOURCE_MANAGER_CPU_REQUEST
  value: 200m
- name: PULP_RESOURCE_MANAGER_CPU_LIMIT
  value: 500m

# pulp-content-app resource requirements
- name: PULP_CONTENT_APP_REPLICAS
  value: '1'
- name: PULP_CONTENT_APP_MEMORY_REQUEST
  value: 1024Mi
- name: PULP_CONTENT_APP_MEMORY_LIMIT
  value: 1536Mi
- name: PULP_CONTENT_APP_CPU_REQUEST
  value: 200m
- name: PULP_CONTENT_APP_CPU_LIMIT
  value: 600m

# pulp-worker resource requirements
- name: PULP_WORKER_REPLICAS
  value: '1'
- name: PULP_WORKER_MEMORY_REQUEST
  value: 256Mi
- name: PULP_WORKER_MEMORY_LIMIT
  value: 512Mi
- name: PULP_WORKER_CPU_REQUEST
  value: 200m
- name: PULP_WORKER_CPU_LIMIT
  value: 500m
