---
apiVersion: v1
kind: Template
metadata:
  name: automation-hub
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: automation-hub
    namespace: automation-hub
  spec:
    # The name of the ClowdEnvironment providing the services
    envName: ${ENV_NAME}

    # The bulk of your App. This is where your running apps will live
    jobs:
      - name: clowder-database-migration
        activeDeadlineSeconds: ${{MIGRATION_JOB_ACTIVE_DEADLINE_SECONDS}}
        restartPolicy: Never
        imagePullSecrets:
          - name: quay-cloudservices-pull
          - name: rh-registry-pull
        volumes:
          - name: settings
            configMap:
              name: galaxy-config
        podSpec:
          name: database-migration-${IMAGE_TAG}
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          args: ['manage', 'migrate']
          resources:
            limits:
              cpu: ${{MIGRATION_JOB_CPU_LIMIT}}
              memory: ${{MIGRATION_JOB_MEMORY_LIMIT}}
            requests:
              cpu: ${{MIGRATION_JOB_CPU_REQUEST}}
              memory: ${{MIGRATION_JOB_MEMORY_REQUEST}}
          volumeMounts:
            - mountPath: /etc/pulp
              name: settings
          env:
            - name: PULP_SECRET_KEY
              value: pulp_secret_key_tmp
            - name: PULP_CONTENT_ORIGIN
              value: pulp_content_origin_tmp
    deployments:
    - name: galaxy-api
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'api']
        initContainers:
          - args:
            - wait-for-migrations
            image: ${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            name: galaxy-api-init
            resources:
              limits:
                cpu: ${{GALAXY_API_CPU_LIMIT}}
                memory: ${{GALAXY_API_MEMORY_LIMIT}}
              requests:
                cpu: ${{GALAXY_API_CPU_REQUEST}}
                memory: ${{GALAXY_API_MEMORY_REQUEST}}
            volumeMounts:
                - mountPath: /etc/pulp
                  name: settings
            env:
            - name: PULP_SECRET_KEY
              value: pulp_secret_key_tmp
            - name: PULP_CONTENT_ORIGIN
              value: pulp_content_origin_tmp
        resources:
          limits:
            cpu: ${{GALAXY_API_CPU_LIMIT}}
            memory: ${{GALAXY_API_MEMORY_LIMIT}}
          requests:
            cpu: ${{GALAXY_API_CPU_REQUEST}}
            memory: ${{GALAXY_API_MEMORY_REQUEST}}
        readinessProbe:
          httpGet:
            path: /_healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 130
          periodSeconds: 30
        name: automation-hub-galaxy-api
        livenessProbe:
          httpGet:
            path: /_healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
          - name: GALAXY_AUTHENTICATION_CLASSES
            value: '["galaxy_ng.app.auth.auth.RHIdentityAuthentication"]'
          - name: GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: 'localhost'
          - name: WITH_MIGRATIONS
            value: '1'
      webServices:
        public:
            enabled: true
    - name: pulp-resource-manager
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'resource-manager']
        initContainers:
        - args:
          - wait-for-migrations
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: pulp-resource-manager-init
          resources:
            limits:
              cpu: ${{PULP_RESOURCE_MANAGER_CPU_LIMIT}}
              memory: ${{PULP_RESOURCE_MANAGER_MEMORY_LIMIT}}
            requests:
              cpu: ${{PULP_RESOURCE_MANAGER_CPU_REQUEST}}
              memory: ${{PULP_RESOURCE_MANAGER_MEMORY_REQUEST}}
          volumeMounts:
          - mountPath: /etc/pulp
            name: settings
          env:
          - name: PULP_SECRET_KEY
            value: pulp_secret_key_tmp
          - name: PULP_CONTENT_ORIGIN
            value: pulp_content_origin_tmp
        resources:
          limits:
            cpu: ${{PULP_RESOURCE_MANAGER_CPU_LIMIT}}
            memory: ${{PULP_RESOURCE_MANAGER_MEMORY_LIMIT}}
          requests:
            cpu: ${{PULP_RESOURCE_MANAGER_CPU_REQUEST}}
            memory: ${{PULP_RESOURCE_MANAGER_MEMORY_REQUEST}}
        env:
          - name: GALAXY_AUTHENTICATION_CLASSES
            value: '["galaxy_ng.app.auth.auth.RHIdentityAuthentication"]'
          - name: GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: 'localhost'
    - name: pulp-content-app
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'content-app']
        initContainers:
        - args:
          - wait-for-migrations
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: ${NAME}-init
          resources:
            limits:
              cpu: ${{PULP_CONTENT_APP_CPU_LIMIT}}
              memory: ${{PULP_CONTENT_APP_MEMORY_LIMIT}}
            requests:
              cpu: ${{PULP_CONTENT_APP_CPU_REQUEST}}
              memory: ${{PULP_CONTENT_APP_MEMORY_REQUEST}}
          volumeMounts:
          - mountPath: /etc/pulp
            name: settings
          env:
          - name: PULP_SECRET_KEY
            value: pulp_secret_key_tmp
          - name: PULP_CONTENT_ORIGIN
            value: pulp_content_origin_tmp
        resources:
          limits:
            cpu: 600m
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        env:
          - name: GALAXY_AUTHENTICATION_CLASSES
            value: '["galaxy_ng.app.auth.auth.RHIdentityAuthentication"]'
          - name: GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: PULP_CONTENT_ORIGIN
            value: 'localhost'
    - name: pulp-worker
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ['run', 'worker']
        initContainers:
        - args:
          - wait-for-migrations
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: ${NAME}-init
          resources:
            limits:
              cpu: ${{PULP_WORKER_CPU_LIMIT}}
              memory: ${{PULP_WORKER_MEMORY_LIMIT}}
            requests:
              cpu: ${{PULP_WORKER_CPU_REQUEST}}
              memory: ${{PULP_WORKER_MEMORY_REQUEST}}
          volumeMounts:
          - mountPath: /etc/pulp
            name: settings
          env:
          - name: PULP_SECRET_KEY
            value: pulp_secret_key_tmp
          - name: PULP_CONTENT_ORIGIN
            value: pulp_content_origin_tmp
        resources:
          limits:
            cpu: ${{PULP_WORKER_CPU_LIMIT}}
            memory: ${{PULP_WORKER_MEMORY_LIMIT}}
          requests:
            cpu: ${{PULP_WORKER_CPU_REQUEST}}
            memory: ${{PULP_WORKER_MEMORY_REQUEST}}
        env:
          - name: GALAXY_AUTHENTICATION_CLASSES
            value: '["galaxy_ng.app.auth.auth.RHIdentityAuthentication"]'
          - name: GALAXY_DEPLOYMENT_MODE
            value: 'insights'
          - name: IMPORTER_MEMORY_REQUEST
            value: 1Gi
          - name: IMPORTER_MEMORY_LIMIT
            value: 2Gi
          - name: IMPORTER_CPU_REQUEST
            value: 500m
          - name: IMPORTER_CPU_LIMIT
            value: 1000m
          - name: PULP_CONTENT_ORIGIN
            value: 'localhost'

    # Creates a database if local mode, or uses RDS in production
    database:
      # Must specify both a name and a major postgres version
      name: automation-hub
      version: 12

    inMemoryDb: true

    objectStore:
      - automation-hub

parameters:
- descripton: Automation Hub image name
  name: IMAGE_NAME
  value: "quay.io/cloudservices/automation-hub-galaxy-ng"
- description: Automation Hub image tag
  name: IMAGE_TAG
  required: true
- description: Clowder ENV
  name: ENV_NAME
  required: true
- name: MIGRATION_JOB_CPU_REQUEST
  value: 200m
  required: true
- name: MIGRATION_JOB_CPU_LIMIT
  value: 1000m
  required: true
- name: MIGRATION_JOB_MEMORY_REQUEST
  value: 512Mi
  required: true
- name: MIGRATION_JOB_MEMORY_LIMIT
  value: 768Mi
  required: true
- name: MIGRATION_JOB_ACTIVE_DEADLINE_SECONDS
  value: "3600"
  required: true
- description: Initial amount of memory the galaxy-api container will request.
  displayName: Memory Request
  name: GALAXY_API_MEMORY_REQUEST
  required: true
  value: 1024Mi
- description: Maximum amount of memory the galaxy-api container can use.
  displayName: Memory Limit
  name: GALAXY_API_MEMORY_LIMIT
  required: true
  value: 1536Mi
- description: Initial amount of cpu the galaxy-api container will request.
  displayName: CPU Request
  name: GALAXY_API_CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the galaxy-api container can use.
  displayName: CPU Limit
  name: GALAXY_API_CPU_LIMIT
  required: true
  value: 600m
- description: Initial amount of memory the pulp-resource-manager container will request.
  displayName: Memory Request
  name: PULP_RESOURCE_MANAGER_MEMORY_REQUEST
  required: true
  value: 128Mi
- description: Maximum amount of memory the pulp-resource-manager container can use.
  displayName: Memory Limit
  name: PULP_RESOURCE_MANAGER_MEMORY_LIMIT
  required: true
  value: 128Mi
- description: Initial amount of cpu the pulp-resource-manager container will request.
  displayName: CPU Request
  name: PULP_RESOURCE_MANAGER_CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of cpu the pulp-resource-manager container can use.
  displayName: CPU Limit
  name: PULP_RESOURCE_MANAGER_CPU_LIMIT
  required: true
  value: 200m
- description: Initial amount of memory the pulp-content-app container will request.
  displayName: Memory Request
  name: PULP_CONTENT_APP_MEMORY_REQUEST
  required: true
  value: 1024Mi
- description: Maximum amount of memory the pulp-content-app container can use.
  displayName: Memory Limit
  name: PULP_CONTENT_APP_MEMORY_LIMIT
  required: true
  value: 1536Mi
- description: Initial amount of cpu the pulp-content-app container will request.
  displayName: CPU Request
  name: PULP_CONTENT_APP_CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the pulp-content-app container can use.
  displayName: CPU Limit
  name: PULP_CONTENT_APP_CPU_LIMIT
  required: true
  value: 600m
- description: Initial amount of memory the pulp-worker container will request.
  displayName: Memory Request
  name: PULP_WORKER_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the pulp-worker container can use.
  displayName: Memory Limit
  name: PULP_WORKER_MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the pulp-worker container will request.
  displayName: CPU Request
  name: PULP_WORKER_CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the pulp-worker container can use.
  displayName: CPU Limit
  name: PULP_WORKER_CPU_LIMIT
  required: true
  value: 500m
