version: "3.7"

services:
  ui:
    build:
      context: "${ANSIBLE_HUB_UI_PATH}"
    ports:
      - "8002:8002"
    volumes:
      - "${ANSIBLE_HUB_UI_PATH}:/hub/app/"
      # Forces npm to ignore the node_node modules in the volume and look
      # for it in ../node_modules instead
      - "nodata:/hub/app/node_modules:ro"
    depends_on:
      - api

volumes:
  nodata: {}
