---
version: "3.7"

services:
  api:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'
    volumes:
      - './standalone-community/galaxy-importer.cfg:/etc/galaxy-importer/galaxy-importer.cfg:z'
  worker:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'
    volumes:
      - './standalone-community/galaxy-importer.cfg:/etc/galaxy-importer/galaxy-importer.cfg:z'
  content-app:
    env_file:
      - './standalone-community/galaxy_ng.env'
      - '../.compose.env'
  galaxy-mirror:
    hostname: galaxy-mirror
    image: jtanner0/galaxy-mirror:3.0
    volumes:
      - './standalone-community/data:/data:rw'
