---
version: "3.7"

services:
  proxy:
    build:
      context: '/Users/dnewswan/code/hub/galaxy_ng/../galaxy_ng/profiles/insights/proxy'
    ports:
      - "8080:8080"
    environment:
      UPSTREAM_PROTO: 'http'
      UPSTREAM_HOST: pulp
      UPSTREAM_PORT: "5001"
      PYTHONUNBUFFERED: 1
      #UPSTREAM_PORT: 5001
    volumes:
      - '/Users/dnewswan/code/hub/galaxy_ng/../galaxy_ng/profiles/insights/proxy:/app:ro'