---
name: Insights
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: Install python requirements required to run integration tests
        run: pip install requests pyyaml

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.17.3'

      - name: create the .compose.env file
        run: rm -f .compose.env; cp .compose.env.example .compose.env

      - name: set the compose profile
        run: sed -i.bak 's/COMPOSE_PROFILE=standalone/COMPOSE_PROFILE=insights/' .compose.env

      - name: workaround github worker permissions issues - disable editable installs
        run: sed -i.bak 's/PIP_EDITABLE_INSTALL=1/PIP_EDITABLE_INSTALL=0/' .compose.env

      - name: workaround github worker permissions issues - disable dev installs
        run: sed -i.bak 's/WITH_DEV_INSTALL=1/WITH_DEV_INSTALL=0/' .compose.env

      - name: require approval
        run: sed -i.bak 's/# PULP_GALAXY_REQUIRE_CONTENT_APPROVAL=false/PULP_GALAXY_REQUIRE_CONTENT_APPROVAL=true/' .compose.env

      - name: enable signing but do not setup a signing service
        run: sed -i.bak 's/ENABLE_SIGNING=1/ENABLE_SIGNING=2/' .compose.env

      - name: build stack
        run: make docker/all

      - name: start the compose stack
        run: ./compose up -d

      - name: give stack some time to spin up
        # run: COMPOSE_INTERACTIVE_NO_CLI=1 python dev/common/poll.py http://localhost:8080/api/automation-hub/pulp/api/v3/status/
        run: sleep 120

      - name: run the integration tests
        run: ./dev/insights/RUN_INTEGRATION.sh
