---
name: Standalone Community
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CHANGES/**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: Install docker-compose
        run: pip3 install --upgrade docker-compose

      - name: create the .compose.env file
        run: rm -f .compose.env; cp .compose.env.example .compose.env

      - name: set the profile to community
        run: sed -i.bak 's/COMPOSE_PROFILE=standalone/COMPOSE_PROFILE=standalone-community/' .compose.env

      - name: workaround github worker permissions issues - disable editable installs
        run: sed -i.bak 's/PIP_EDITABLE_INSTALL=1/PIP_EDITABLE_INSTALL=0/' .compose.env

      - name: workaround github worker permissions issues - disable dev installs
        run: sed -i.bak 's/WITH_DEV_INSTALL=1/WITH_DEV_INSTALL=0/' .compose.env

      - name: set the github key
        run: echo "SOCIAL_AUTH_GITHUB_KEY='abcd1234'" >> .compose.env

      - name: set the github secret
        run: echo "SOCIAL_AUTH_GITHUB_SECRET='abcd1234'" >> .compose.env

      - name: set the github base url
        run: echo "SOCIAL_AUTH_GITHUB_BASE_URL='http://github:8082'" >> .compose.env

      - name: set the github api url
        run: echo "SOCIAL_AUTH_GITHUB_API_URL='http://github:8082'" >> .compose.env

      - name: build everything and load data
        run: make docker/all

      - name: start the compose stack
        run: ./compose up -d

      - name: give stack some time to spin up
        run: sleep 120

      - name: run the integration tests
        run: DUMP_LOGS=1 ./dev/standalone-community/RUN_INTEGRATION.sh
