name: Galaxy Custom CI


# Events that trigger workflow
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'  # double asterisk would include this workflow on push to a fork


# Jobs can run sequentially or in parallel
jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.after }}  # for PR avoids checking out merge commit
        fetch-depth: 0  # include all history

    - name: Run script to validate commits for both pull request and a push
      env:
        GITHUB_PR_COMMITS_URL: ${{ github.event.pull_request.commits_url }}
        START_COMMIT: ${{ github.event.before }}
        END_COMMIT: ${{ github.event.after }}
      run: |
        sh .github/workflows/scripts/check_commits.sh
