name: Issue Handler

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Point user to Jira Issue Tracker
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Galaxy NG issues moved to [https://issues.redhat.com/projects/AAH/issues](https://issues.redhat.com/projects/AAH/issues) please open this issue there."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: Auto-closing issue
        token: ${{ secrets.GITHUB_TOKEN }}
