name: Sync to Ansible Galaxy NG

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to sync from'
        required: false
        default: 'main'
        type: string
      target_branch:
        description: 'Target branch to sync to'
        required: false
        default: 'main'
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.repository, 'ansible-automation-platform')
    steps:
      - name: Generate ephemeral read-only token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ANSIBLE_CICD_BOT_ORG_RW_TOKEN_APP_ID }}
          private-key: ${{ secrets.ANSIBLE_CICD_BOT_ORG_RW_TOKEN_PRIVATE_KEY }}
          permissions: >-
            {"contents": "read"}

      - name: Force push to Ansible repository
        run: |
          gh repo clone ansible-automation-platform/galaxy_ng
          cd galaxy_ng
          git checkout "$SOURCE_BRANCH"
          git status

          git push "https://${PUSH_TOKEN}@github.com/ansible/galaxy_ng.git" "${SOURCE_BRANCH}:${TARGET_BRANCH}" --force
        env:
          SOURCE_BRANCH: ${{ github.event.inputs.source_branch || 'main' }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch || 'main' }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PUSH_TOKEN: ${{ secrets.ANSIBLE_FG_AAP_HUB_CI_BOT_ACTIONS }}
