name: Sync to Ansible Galaxy NG

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to sync from'
        required: false
        default: 'main'
        type: string
      target_branch:
        description: 'Target branch to sync to'
        required: false
        default: 'main'
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.repository, 'ansible-automation-platform')
    steps:
      - name: Force push to Ansible repository
        run: |
          SOURCE_BRANCH="${{ github.event.inputs.source_branch || 'main' }}"
          TARGET_BRANCH="${{ github.event.inputs.target_branch || 'main' }}"

          export GH_TOKEN=${{ secrets.AAP_ORG_FG_SCHMIDTD_RW_ACTIONS }}
          gh repo clone ansible-automation-platform/galaxy_ng
          cd galaxy_ng
          git checkout $SOURCE_BRANCH
          git status

          git push https://${{ secrets.FAO_TOKEN }}@github.com/ansible/galaxy_ng.git ${SOURCE_BRANCH}:${TARGET_BRANCH} --force
